group: edge

sudo: required

dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev

env:
  - CC=gcc-4.8 CXX=g++-4.8 CPP=cpp-4.8 CXXCPP=cpp-4.8

before_install:

  # download and install bazel
  - wget -q 'https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-linux-x86_64.sh'
  - chmod +x bazel-0.2.3-installer-linux-x86_64.sh
  - ./bazel-0.2.3-installer-linux-x86_64.sh --user

before_script:
  # required for building the website docs
  - (cd website && npm install && npm install gulp && which gulp)
  - wget -q https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

script:
  - for p in $(dpkg -l | awk '/lzma/ { print $2 }'); do echo $p; dpkg -L $p; done
  - which gcc-4.8
  - gcc --version
  - which g++-4.8
  - g++ --version
  - scripts/travis/ci.sh

after_failure:
  - find . -name heron_build.txt -print -exec cat {} \;
